// Code generated by fin-protoc. DO NOT EDIT.
package com.finproto.bjse.trade.messages;

import com.finproto.codec.BinaryCodec;
import io.netty.buffer.ByteBuf;
import java.util.Objects;

public class AllegeQuoteExtend070 implements BinaryCodec {
  private byte cashMargin;
  private String counterPartyPbuid;

  public byte getCashMargin() {
    return this.cashMargin;
  }

  public void setCashMargin(byte cashMargin) {
    this.cashMargin = cashMargin;
  }

  public String getCounterPartyPbuid() {
    return this.counterPartyPbuid;
  }

  public void setCounterPartyPbuid(String counterPartyPbuid) {
    this.counterPartyPbuid = counterPartyPbuid;
  }

  @Override
  public void encode(ByteBuf byteBuf) {
    byteBuf.writeByte(this.cashMargin);
    writeFixedString(byteBuf, this.counterPartyPbuid, 6);
  }

  @Override
  public void decode(ByteBuf byteBuf) {
    this.cashMargin = byteBuf.readByte();
    this.counterPartyPbuid = readFixedString(byteBuf, 6);
  }

  @Override
  public int hashCode() {
    return Objects.hash(cashMargin, counterPartyPbuid);
  }

  @Override
  public boolean equals(Object obj) {
    if (this == obj) {
      return true;
    }
    if (null == obj || getClass() != obj.getClass()) {
      return false;
    }
    AllegeQuoteExtend070 orther_ = (AllegeQuoteExtend070) obj;
    return Objects.equals(cashMargin, orther_.cashMargin)
        && Objects.equals(counterPartyPbuid, orther_.counterPartyPbuid);
  }

  @Override
  public String toString() {
    return "AllegeQuoteExtend070 ["
        + "cashMargin="
        + this.cashMargin
        + ", counterPartyPbuid="
        + this.counterPartyPbuid
        + "]";
  }
}
