// Code generated by fin-protoc. DO NOT EDIT.
package com.finproto.bjse.trade.messages;

import com.finproto.codec.BinaryCodec;
import io.netty.buffer.ByteBuf;
import java.util.Objects;

public class AllegeQuoteResponse implements BinaryCodec {
  private int partitionNo;
  private long reportIndex;
  private String applId;
  private String reportingPbuid;
  private String submittingPbuid;
  private String securityId;
  private String securityIdsource;
  private short ownerType;
  private String clearingFirm;
  private long transactTime;
  private String userInfo;
  private String orderId;
  private String execId;
  private String clOrdId;
  private String accountId;
  private String quoteId;
  private String quoteRespId;
  private byte quoteRespType;
  private byte privateQuote;
  private long orderQty;
  private long price;
  private long validUntilTime;
  private byte quoteType;
  private byte priceType;

  public int getPartitionNo() {
    return this.partitionNo;
  }

  public void setPartitionNo(int partitionNo) {
    this.partitionNo = partitionNo;
  }

  public long getReportIndex() {
    return this.reportIndex;
  }

  public void setReportIndex(long reportIndex) {
    this.reportIndex = reportIndex;
  }

  public String getApplId() {
    return this.applId;
  }

  public void setApplId(String applId) {
    this.applId = applId;
  }

  public String getReportingPbuid() {
    return this.reportingPbuid;
  }

  public void setReportingPbuid(String reportingPbuid) {
    this.reportingPbuid = reportingPbuid;
  }

  public String getSubmittingPbuid() {
    return this.submittingPbuid;
  }

  public void setSubmittingPbuid(String submittingPbuid) {
    this.submittingPbuid = submittingPbuid;
  }

  public String getSecurityId() {
    return this.securityId;
  }

  public void setSecurityId(String securityId) {
    this.securityId = securityId;
  }

  public String getSecurityIdsource() {
    return this.securityIdsource;
  }

  public void setSecurityIdsource(String securityIdsource) {
    this.securityIdsource = securityIdsource;
  }

  public short getOwnerType() {
    return this.ownerType;
  }

  public void setOwnerType(short ownerType) {
    this.ownerType = ownerType;
  }

  public String getClearingFirm() {
    return this.clearingFirm;
  }

  public void setClearingFirm(String clearingFirm) {
    this.clearingFirm = clearingFirm;
  }

  public long getTransactTime() {
    return this.transactTime;
  }

  public void setTransactTime(long transactTime) {
    this.transactTime = transactTime;
  }

  public String getUserInfo() {
    return this.userInfo;
  }

  public void setUserInfo(String userInfo) {
    this.userInfo = userInfo;
  }

  public String getOrderId() {
    return this.orderId;
  }

  public void setOrderId(String orderId) {
    this.orderId = orderId;
  }

  public String getExecId() {
    return this.execId;
  }

  public void setExecId(String execId) {
    this.execId = execId;
  }

  public String getClOrdId() {
    return this.clOrdId;
  }

  public void setClOrdId(String clOrdId) {
    this.clOrdId = clOrdId;
  }

  public String getAccountId() {
    return this.accountId;
  }

  public void setAccountId(String accountId) {
    this.accountId = accountId;
  }

  public String getQuoteId() {
    return this.quoteId;
  }

  public void setQuoteId(String quoteId) {
    this.quoteId = quoteId;
  }

  public String getQuoteRespId() {
    return this.quoteRespId;
  }

  public void setQuoteRespId(String quoteRespId) {
    this.quoteRespId = quoteRespId;
  }

  public byte getQuoteRespType() {
    return this.quoteRespType;
  }

  public void setQuoteRespType(byte quoteRespType) {
    this.quoteRespType = quoteRespType;
  }

  public byte getPrivateQuote() {
    return this.privateQuote;
  }

  public void setPrivateQuote(byte privateQuote) {
    this.privateQuote = privateQuote;
  }

  public long getOrderQty() {
    return this.orderQty;
  }

  public void setOrderQty(long orderQty) {
    this.orderQty = orderQty;
  }

  public long getPrice() {
    return this.price;
  }

  public void setPrice(long price) {
    this.price = price;
  }

  public long getValidUntilTime() {
    return this.validUntilTime;
  }

  public void setValidUntilTime(long validUntilTime) {
    this.validUntilTime = validUntilTime;
  }

  public byte getQuoteType() {
    return this.quoteType;
  }

  public void setQuoteType(byte quoteType) {
    this.quoteType = quoteType;
  }

  public byte getPriceType() {
    return this.priceType;
  }

  public void setPriceType(byte priceType) {
    this.priceType = priceType;
  }

  @Override
  public void encode(ByteBuf byteBuf) {
    byteBuf.writeIntLE(this.partitionNo);
    byteBuf.writeLongLE(this.reportIndex);
    writeFixedString(byteBuf, this.applId, 3);
    writeFixedString(byteBuf, this.reportingPbuid, 6);
    writeFixedString(byteBuf, this.submittingPbuid, 6);
    writeFixedString(byteBuf, this.securityId, 8);
    writeFixedString(byteBuf, this.securityIdsource, 4);
    byteBuf.writeShortLE(this.ownerType);
    writeFixedString(byteBuf, this.clearingFirm, 2);
    byteBuf.writeLongLE(this.transactTime);
    writeFixedString(byteBuf, this.userInfo, 32);
    writeFixedString(byteBuf, this.orderId, 16);
    writeFixedString(byteBuf, this.execId, 16);
    writeFixedString(byteBuf, this.clOrdId, 10);
    writeFixedString(byteBuf, this.accountId, 10);
    writeFixedString(byteBuf, this.quoteId, 10);
    writeFixedString(byteBuf, this.quoteRespId, 10);
    byteBuf.writeByte(this.quoteRespType);
    byteBuf.writeByte(this.privateQuote);
    byteBuf.writeLongLE(this.orderQty);
    byteBuf.writeLongLE(this.price);
    byteBuf.writeLongLE(this.validUntilTime);
    byteBuf.writeByte(this.quoteType);
    byteBuf.writeByte(this.priceType);
  }

  @Override
  public void decode(ByteBuf byteBuf) {
    this.partitionNo = byteBuf.readIntLE();
    this.reportIndex = byteBuf.readLongLE();
    this.applId = readFixedString(byteBuf, 3);
    this.reportingPbuid = readFixedString(byteBuf, 6);
    this.submittingPbuid = readFixedString(byteBuf, 6);
    this.securityId = readFixedString(byteBuf, 8);
    this.securityIdsource = readFixedString(byteBuf, 4);
    this.ownerType = byteBuf.readShortLE();
    this.clearingFirm = readFixedString(byteBuf, 2);
    this.transactTime = byteBuf.readLongLE();
    this.userInfo = readFixedString(byteBuf, 32);
    this.orderId = readFixedString(byteBuf, 16);
    this.execId = readFixedString(byteBuf, 16);
    this.clOrdId = readFixedString(byteBuf, 10);
    this.accountId = readFixedString(byteBuf, 10);
    this.quoteId = readFixedString(byteBuf, 10);
    this.quoteRespId = readFixedString(byteBuf, 10);
    this.quoteRespType = byteBuf.readByte();
    this.privateQuote = byteBuf.readByte();
    this.orderQty = byteBuf.readLongLE();
    this.price = byteBuf.readLongLE();
    this.validUntilTime = byteBuf.readLongLE();
    this.quoteType = byteBuf.readByte();
    this.priceType = byteBuf.readByte();
  }

  @Override
  public int hashCode() {
    return Objects.hash(
        partitionNo,
        reportIndex,
        applId,
        reportingPbuid,
        submittingPbuid,
        securityId,
        securityIdsource,
        ownerType,
        clearingFirm,
        transactTime,
        userInfo,
        orderId,
        execId,
        clOrdId,
        accountId,
        quoteId,
        quoteRespId,
        quoteRespType,
        privateQuote,
        orderQty,
        price,
        validUntilTime,
        quoteType,
        priceType);
  }

  @Override
  public boolean equals(Object obj) {
    if (this == obj) {
      return true;
    }
    if (null == obj || getClass() != obj.getClass()) {
      return false;
    }
    AllegeQuoteResponse orther_ = (AllegeQuoteResponse) obj;
    return Objects.equals(partitionNo, orther_.partitionNo)
        && Objects.equals(reportIndex, orther_.reportIndex)
        && Objects.equals(applId, orther_.applId)
        && Objects.equals(reportingPbuid, orther_.reportingPbuid)
        && Objects.equals(submittingPbuid, orther_.submittingPbuid)
        && Objects.equals(securityId, orther_.securityId)
        && Objects.equals(securityIdsource, orther_.securityIdsource)
        && Objects.equals(ownerType, orther_.ownerType)
        && Objects.equals(clearingFirm, orther_.clearingFirm)
        && Objects.equals(transactTime, orther_.transactTime)
        && Objects.equals(userInfo, orther_.userInfo)
        && Objects.equals(orderId, orther_.orderId)
        && Objects.equals(execId, orther_.execId)
        && Objects.equals(clOrdId, orther_.clOrdId)
        && Objects.equals(accountId, orther_.accountId)
        && Objects.equals(quoteId, orther_.quoteId)
        && Objects.equals(quoteRespId, orther_.quoteRespId)
        && Objects.equals(quoteRespType, orther_.quoteRespType)
        && Objects.equals(privateQuote, orther_.privateQuote)
        && Objects.equals(orderQty, orther_.orderQty)
        && Objects.equals(price, orther_.price)
        && Objects.equals(validUntilTime, orther_.validUntilTime)
        && Objects.equals(quoteType, orther_.quoteType)
        && Objects.equals(priceType, orther_.priceType);
  }

  @Override
  public String toString() {
    return "AllegeQuoteResponse ["
        + "partitionNo="
        + this.partitionNo
        + ", reportIndex="
        + this.reportIndex
        + ", applId="
        + this.applId
        + ", reportingPbuid="
        + this.reportingPbuid
        + ", submittingPbuid="
        + this.submittingPbuid
        + ", securityId="
        + this.securityId
        + ", securityIdsource="
        + this.securityIdsource
        + ", ownerType="
        + this.ownerType
        + ", clearingFirm="
        + this.clearingFirm
        + ", transactTime="
        + this.transactTime
        + ", userInfo="
        + this.userInfo
        + ", orderId="
        + this.orderId
        + ", execId="
        + this.execId
        + ", clOrdId="
        + this.clOrdId
        + ", accountId="
        + this.accountId
        + ", quoteId="
        + this.quoteId
        + ", quoteRespId="
        + this.quoteRespId
        + ", quoteRespType="
        + this.quoteRespType
        + ", privateQuote="
        + this.privateQuote
        + ", orderQty="
        + this.orderQty
        + ", price="
        + this.price
        + ", validUntilTime="
        + this.validUntilTime
        + ", quoteType="
        + this.quoteType
        + ", priceType="
        + this.priceType
        + "]";
  }
}
