// Code generated by fin-protoc. DO NOT EDIT.
package com.finproto.bjse.trade.messages;

import com.finproto.codec.BinaryCodec;
import io.netty.buffer.ByteBuf;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.Supplier;

public class AllegeQuote implements BinaryCodec {
  private int partitionNo;
  private long reportIndex;
  private String applId;
  private String reportingPbuid;
  private String submittingPbuid;
  private String securityId;
  private String securityIdsource;
  private short ownerType;
  private String clearingFirm;
  private long transactTime;
  private String userInfo;
  private String orderId;
  private String execId;
  private String clOrdId;
  private String accountId;
  private String quoteReqId;
  private String quoteId;
  private String quoteRespId;
  private byte quoteType;
  private long bidPx;
  private long offerPx;
  private long bidSize;
  private long offerSize;
  private byte privateQuote;
  private long validUntilTime;
  private byte priceType;
  private String memo;
  private BinaryCodec applExtend;

  public int getPartitionNo() {
    return this.partitionNo;
  }

  public void setPartitionNo(int partitionNo) {
    this.partitionNo = partitionNo;
  }

  public long getReportIndex() {
    return this.reportIndex;
  }

  public void setReportIndex(long reportIndex) {
    this.reportIndex = reportIndex;
  }

  public String getApplId() {
    return this.applId;
  }

  public void setApplId(String applId) {
    this.applId = applId;
  }

  public String getReportingPbuid() {
    return this.reportingPbuid;
  }

  public void setReportingPbuid(String reportingPbuid) {
    this.reportingPbuid = reportingPbuid;
  }

  public String getSubmittingPbuid() {
    return this.submittingPbuid;
  }

  public void setSubmittingPbuid(String submittingPbuid) {
    this.submittingPbuid = submittingPbuid;
  }

  public String getSecurityId() {
    return this.securityId;
  }

  public void setSecurityId(String securityId) {
    this.securityId = securityId;
  }

  public String getSecurityIdsource() {
    return this.securityIdsource;
  }

  public void setSecurityIdsource(String securityIdsource) {
    this.securityIdsource = securityIdsource;
  }

  public short getOwnerType() {
    return this.ownerType;
  }

  public void setOwnerType(short ownerType) {
    this.ownerType = ownerType;
  }

  public String getClearingFirm() {
    return this.clearingFirm;
  }

  public void setClearingFirm(String clearingFirm) {
    this.clearingFirm = clearingFirm;
  }

  public long getTransactTime() {
    return this.transactTime;
  }

  public void setTransactTime(long transactTime) {
    this.transactTime = transactTime;
  }

  public String getUserInfo() {
    return this.userInfo;
  }

  public void setUserInfo(String userInfo) {
    this.userInfo = userInfo;
  }

  public String getOrderId() {
    return this.orderId;
  }

  public void setOrderId(String orderId) {
    this.orderId = orderId;
  }

  public String getExecId() {
    return this.execId;
  }

  public void setExecId(String execId) {
    this.execId = execId;
  }

  public String getClOrdId() {
    return this.clOrdId;
  }

  public void setClOrdId(String clOrdId) {
    this.clOrdId = clOrdId;
  }

  public String getAccountId() {
    return this.accountId;
  }

  public void setAccountId(String accountId) {
    this.accountId = accountId;
  }

  public String getQuoteReqId() {
    return this.quoteReqId;
  }

  public void setQuoteReqId(String quoteReqId) {
    this.quoteReqId = quoteReqId;
  }

  public String getQuoteId() {
    return this.quoteId;
  }

  public void setQuoteId(String quoteId) {
    this.quoteId = quoteId;
  }

  public String getQuoteRespId() {
    return this.quoteRespId;
  }

  public void setQuoteRespId(String quoteRespId) {
    this.quoteRespId = quoteRespId;
  }

  public byte getQuoteType() {
    return this.quoteType;
  }

  public void setQuoteType(byte quoteType) {
    this.quoteType = quoteType;
  }

  public long getBidPx() {
    return this.bidPx;
  }

  public void setBidPx(long bidPx) {
    this.bidPx = bidPx;
  }

  public long getOfferPx() {
    return this.offerPx;
  }

  public void setOfferPx(long offerPx) {
    this.offerPx = offerPx;
  }

  public long getBidSize() {
    return this.bidSize;
  }

  public void setBidSize(long bidSize) {
    this.bidSize = bidSize;
  }

  public long getOfferSize() {
    return this.offerSize;
  }

  public void setOfferSize(long offerSize) {
    this.offerSize = offerSize;
  }

  public byte getPrivateQuote() {
    return this.privateQuote;
  }

  public void setPrivateQuote(byte privateQuote) {
    this.privateQuote = privateQuote;
  }

  public long getValidUntilTime() {
    return this.validUntilTime;
  }

  public void setValidUntilTime(long validUntilTime) {
    this.validUntilTime = validUntilTime;
  }

  public byte getPriceType() {
    return this.priceType;
  }

  public void setPriceType(byte priceType) {
    this.priceType = priceType;
  }

  public String getMemo() {
    return this.memo;
  }

  public void setMemo(String memo) {
    this.memo = memo;
  }

  public BinaryCodec getApplExtend() {
    return this.applExtend;
  }

  public void setApplExtend(BinaryCodec applExtend) {
    this.applExtend = applExtend;
  }

  @Override
  public void encode(ByteBuf byteBuf) {
    byteBuf.writeIntLE(this.partitionNo);
    byteBuf.writeLongLE(this.reportIndex);
    writeFixedString(byteBuf, this.applId, 3);
    writeFixedString(byteBuf, this.reportingPbuid, 6);
    writeFixedString(byteBuf, this.submittingPbuid, 6);
    writeFixedString(byteBuf, this.securityId, 8);
    writeFixedString(byteBuf, this.securityIdsource, 4);
    byteBuf.writeShortLE(this.ownerType);
    writeFixedString(byteBuf, this.clearingFirm, 2);
    byteBuf.writeLongLE(this.transactTime);
    writeFixedString(byteBuf, this.userInfo, 32);
    writeFixedString(byteBuf, this.orderId, 16);
    writeFixedString(byteBuf, this.execId, 16);
    writeFixedString(byteBuf, this.clOrdId, 10);
    writeFixedString(byteBuf, this.accountId, 10);
    writeFixedString(byteBuf, this.quoteReqId, 10);
    writeFixedString(byteBuf, this.quoteId, 10);
    writeFixedString(byteBuf, this.quoteRespId, 10);
    byteBuf.writeByte(this.quoteType);
    byteBuf.writeLongLE(this.bidPx);
    byteBuf.writeLongLE(this.offerPx);
    byteBuf.writeLongLE(this.bidSize);
    byteBuf.writeLongLE(this.offerSize);
    byteBuf.writeByte(this.privateQuote);
    byteBuf.writeLongLE(this.validUntilTime);
    byteBuf.writeByte(this.priceType);
    writeFixedString(byteBuf, this.memo, 120);
    if (null != this.applExtend) {
      this.applExtend.encode(byteBuf);
    }
  }

  @Override
  public void decode(ByteBuf byteBuf) {
    this.partitionNo = byteBuf.readIntLE();
    this.reportIndex = byteBuf.readLongLE();
    this.applId = readFixedString(byteBuf, 3);
    this.reportingPbuid = readFixedString(byteBuf, 6);
    this.submittingPbuid = readFixedString(byteBuf, 6);
    this.securityId = readFixedString(byteBuf, 8);
    this.securityIdsource = readFixedString(byteBuf, 4);
    this.ownerType = byteBuf.readShortLE();
    this.clearingFirm = readFixedString(byteBuf, 2);
    this.transactTime = byteBuf.readLongLE();
    this.userInfo = readFixedString(byteBuf, 32);
    this.orderId = readFixedString(byteBuf, 16);
    this.execId = readFixedString(byteBuf, 16);
    this.clOrdId = readFixedString(byteBuf, 10);
    this.accountId = readFixedString(byteBuf, 10);
    this.quoteReqId = readFixedString(byteBuf, 10);
    this.quoteId = readFixedString(byteBuf, 10);
    this.quoteRespId = readFixedString(byteBuf, 10);
    this.quoteType = byteBuf.readByte();
    this.bidPx = byteBuf.readLongLE();
    this.offerPx = byteBuf.readLongLE();
    this.bidSize = byteBuf.readLongLE();
    this.offerSize = byteBuf.readLongLE();
    this.privateQuote = byteBuf.readByte();
    this.validUntilTime = byteBuf.readLongLE();
    this.priceType = byteBuf.readByte();
    this.memo = readFixedString(byteBuf, 120);
    this.applExtend = ApplExtendMessageFactory.getInstance().create(this.applId);
    this.applExtend.decode(byteBuf);
  }

  @Override
  public int hashCode() {
    return Objects.hash(
        partitionNo,
        reportIndex,
        applId,
        reportingPbuid,
        submittingPbuid,
        securityId,
        securityIdsource,
        ownerType,
        clearingFirm,
        transactTime,
        userInfo,
        orderId,
        execId,
        clOrdId,
        accountId,
        quoteReqId,
        quoteId,
        quoteRespId,
        quoteType,
        bidPx,
        offerPx,
        bidSize,
        offerSize,
        privateQuote,
        validUntilTime,
        priceType,
        memo,
        applExtend);
  }

  @Override
  public boolean equals(Object obj) {
    if (this == obj) {
      return true;
    }
    if (null == obj || getClass() != obj.getClass()) {
      return false;
    }
    AllegeQuote orther_ = (AllegeQuote) obj;
    return Objects.equals(partitionNo, orther_.partitionNo)
        && Objects.equals(reportIndex, orther_.reportIndex)
        && Objects.equals(applId, orther_.applId)
        && Objects.equals(reportingPbuid, orther_.reportingPbuid)
        && Objects.equals(submittingPbuid, orther_.submittingPbuid)
        && Objects.equals(securityId, orther_.securityId)
        && Objects.equals(securityIdsource, orther_.securityIdsource)
        && Objects.equals(ownerType, orther_.ownerType)
        && Objects.equals(clearingFirm, orther_.clearingFirm)
        && Objects.equals(transactTime, orther_.transactTime)
        && Objects.equals(userInfo, orther_.userInfo)
        && Objects.equals(orderId, orther_.orderId)
        && Objects.equals(execId, orther_.execId)
        && Objects.equals(clOrdId, orther_.clOrdId)
        && Objects.equals(accountId, orther_.accountId)
        && Objects.equals(quoteReqId, orther_.quoteReqId)
        && Objects.equals(quoteId, orther_.quoteId)
        && Objects.equals(quoteRespId, orther_.quoteRespId)
        && Objects.equals(quoteType, orther_.quoteType)
        && Objects.equals(bidPx, orther_.bidPx)
        && Objects.equals(offerPx, orther_.offerPx)
        && Objects.equals(bidSize, orther_.bidSize)
        && Objects.equals(offerSize, orther_.offerSize)
        && Objects.equals(privateQuote, orther_.privateQuote)
        && Objects.equals(validUntilTime, orther_.validUntilTime)
        && Objects.equals(priceType, orther_.priceType)
        && Objects.equals(memo, orther_.memo)
        && Objects.equals(applExtend, orther_.applExtend);
  }

  @Override
  public String toString() {
    return "AllegeQuote ["
        + "partitionNo="
        + this.partitionNo
        + ", reportIndex="
        + this.reportIndex
        + ", applId="
        + this.applId
        + ", reportingPbuid="
        + this.reportingPbuid
        + ", submittingPbuid="
        + this.submittingPbuid
        + ", securityId="
        + this.securityId
        + ", securityIdsource="
        + this.securityIdsource
        + ", ownerType="
        + this.ownerType
        + ", clearingFirm="
        + this.clearingFirm
        + ", transactTime="
        + this.transactTime
        + ", userInfo="
        + this.userInfo
        + ", orderId="
        + this.orderId
        + ", execId="
        + this.execId
        + ", clOrdId="
        + this.clOrdId
        + ", accountId="
        + this.accountId
        + ", quoteReqId="
        + this.quoteReqId
        + ", quoteId="
        + this.quoteId
        + ", quoteRespId="
        + this.quoteRespId
        + ", quoteType="
        + this.quoteType
        + ", bidPx="
        + this.bidPx
        + ", offerPx="
        + this.offerPx
        + ", bidSize="
        + this.bidSize
        + ", offerSize="
        + this.offerSize
        + ", privateQuote="
        + this.privateQuote
        + ", validUntilTime="
        + this.validUntilTime
        + ", priceType="
        + this.priceType
        + ", memo="
        + this.memo
        + ", applExtend="
        + this.applExtend
        + "]";
  }

  public static enum ApplExtendMessageFactory {
    INSTANCE;
    private final Map<String, Supplier<BinaryCodec>> applExtendMap = new HashMap<>();

    static {
      getInstance().register("070", AllegeQuoteExtend070::new);
    }

    public BinaryCodec create(String applId) {
      Supplier<BinaryCodec> supplier = applExtendMap.get(applId);
      if (null == supplier) {
        throw new IllegalArgumentException("Unsupported ApplID:" + applId);
      }
      return supplier.get();
    }

    public void register(String applId, Supplier<BinaryCodec> supplier) {
      applExtendMap.put(applId, supplier);
    }

    public boolean remove(String applId) {
      return null != applExtendMap.remove(applId);
    }

    public static ApplExtendMessageFactory getInstance() {
      return INSTANCE;
    }
  }
}
