// Code generated by fin-protoc. DO NOT EDIT.
package com.finproto.bjse.trade.messages;

import com.finproto.codec.BinaryCodec;
import io.netty.buffer.ByteBuf;
import java.util.Objects;

public class ConfirmExtend010 implements BinaryCodec {
  private long stopPx;
  private long minQty;
  private short maxPriceLevels;
  private String timeInForce;
  private String cashMargin;

  public long getStopPx() {
    return this.stopPx;
  }

  public void setStopPx(long stopPx) {
    this.stopPx = stopPx;
  }

  public long getMinQty() {
    return this.minQty;
  }

  public void setMinQty(long minQty) {
    this.minQty = minQty;
  }

  public short getMaxPriceLevels() {
    return this.maxPriceLevels;
  }

  public void setMaxPriceLevels(short maxPriceLevels) {
    this.maxPriceLevels = maxPriceLevels;
  }

  public String getTimeInForce() {
    return this.timeInForce;
  }

  public void setTimeInForce(String timeInForce) {
    this.timeInForce = timeInForce;
  }

  public String getCashMargin() {
    return this.cashMargin;
  }

  public void setCashMargin(String cashMargin) {
    this.cashMargin = cashMargin;
  }

  @Override
  public void encode(ByteBuf byteBuf) {
    byteBuf.writeLongLE(this.stopPx);
    byteBuf.writeLongLE(this.minQty);
    byteBuf.writeShortLE(this.maxPriceLevels);
    writeFixedString(byteBuf, this.timeInForce, 1);
    writeFixedString(byteBuf, this.cashMargin, 1);
  }

  @Override
  public void decode(ByteBuf byteBuf) {
    this.stopPx = byteBuf.readLongLE();
    this.minQty = byteBuf.readLongLE();
    this.maxPriceLevels = byteBuf.readShortLE();
    this.timeInForce = readFixedString(byteBuf, 1);
    this.cashMargin = readFixedString(byteBuf, 1);
  }

  @Override
  public int hashCode() {
    return Objects.hash(stopPx, minQty, maxPriceLevels, timeInForce, cashMargin);
  }

  @Override
  public boolean equals(Object obj) {
    if (this == obj) {
      return true;
    }
    if (null == obj || getClass() != obj.getClass()) {
      return false;
    }
    ConfirmExtend010 orther_ = (ConfirmExtend010) obj;
    return Objects.equals(stopPx, orther_.stopPx)
        && Objects.equals(minQty, orther_.minQty)
        && Objects.equals(maxPriceLevels, orther_.maxPriceLevels)
        && Objects.equals(timeInForce, orther_.timeInForce)
        && Objects.equals(cashMargin, orther_.cashMargin);
  }

  @Override
  public String toString() {
    return "ConfirmExtend010 ["
        + "stopPx="
        + this.stopPx
        + ", minQty="
        + this.minQty
        + ", maxPriceLevels="
        + this.maxPriceLevels
        + ", timeInForce="
        + this.timeInForce
        + ", cashMargin="
        + this.cashMargin
        + "]";
  }
}
