// Code generated by fin-protoc. DO NOT EDIT.
package com.finproto.bjse.trade.messages;

import com.finproto.codec.BinaryCodec;
import io.netty.buffer.ByteBuf;
import java.util.Objects;

public class Extend010 implements BinaryCodec {
  private long stopPx;
  private long minQty;
  private short maxPriceLevels;
  private byte timeInForce;
  private byte cashMargin;
  private byte settlType;
  private byte settlPeriod;

  public long getStopPx() {
    return this.stopPx;
  }

  public void setStopPx(long stopPx) {
    this.stopPx = stopPx;
  }

  public long getMinQty() {
    return this.minQty;
  }

  public void setMinQty(long minQty) {
    this.minQty = minQty;
  }

  public short getMaxPriceLevels() {
    return this.maxPriceLevels;
  }

  public void setMaxPriceLevels(short maxPriceLevels) {
    this.maxPriceLevels = maxPriceLevels;
  }

  public byte getTimeInForce() {
    return this.timeInForce;
  }

  public void setTimeInForce(byte timeInForce) {
    this.timeInForce = timeInForce;
  }

  public byte getCashMargin() {
    return this.cashMargin;
  }

  public void setCashMargin(byte cashMargin) {
    this.cashMargin = cashMargin;
  }

  public byte getSettlType() {
    return this.settlType;
  }

  public void setSettlType(byte settlType) {
    this.settlType = settlType;
  }

  public byte getSettlPeriod() {
    return this.settlPeriod;
  }

  public void setSettlPeriod(byte settlPeriod) {
    this.settlPeriod = settlPeriod;
  }

  @Override
  public void encode(ByteBuf byteBuf) {
    byteBuf.writeLongLE(this.stopPx);
    byteBuf.writeLongLE(this.minQty);
    byteBuf.writeShortLE(this.maxPriceLevels);
    byteBuf.writeByte(this.timeInForce);
    byteBuf.writeByte(this.cashMargin);
    byteBuf.writeByte(this.settlType);
    byteBuf.writeByte(this.settlPeriod);
  }

  @Override
  public void decode(ByteBuf byteBuf) {
    this.stopPx = byteBuf.readLongLE();
    this.minQty = byteBuf.readLongLE();
    this.maxPriceLevels = byteBuf.readShortLE();
    this.timeInForce = byteBuf.readByte();
    this.cashMargin = byteBuf.readByte();
    this.settlType = byteBuf.readByte();
    this.settlPeriod = byteBuf.readByte();
  }

  @Override
  public int hashCode() {
    return Objects.hash(
        stopPx, minQty, maxPriceLevels, timeInForce, cashMargin, settlType, settlPeriod);
  }

  @Override
  public boolean equals(Object obj) {
    if (this == obj) {
      return true;
    }
    if (null == obj || getClass() != obj.getClass()) {
      return false;
    }
    Extend010 orther_ = (Extend010) obj;
    return Objects.equals(stopPx, orther_.stopPx)
        && Objects.equals(minQty, orther_.minQty)
        && Objects.equals(maxPriceLevels, orther_.maxPriceLevels)
        && Objects.equals(timeInForce, orther_.timeInForce)
        && Objects.equals(cashMargin, orther_.cashMargin)
        && Objects.equals(settlType, orther_.settlType)
        && Objects.equals(settlPeriod, orther_.settlPeriod);
  }

  @Override
  public String toString() {
    return "Extend010 ["
        + "stopPx="
        + this.stopPx
        + ", minQty="
        + this.minQty
        + ", maxPriceLevels="
        + this.maxPriceLevels
        + ", timeInForce="
        + this.timeInForce
        + ", cashMargin="
        + this.cashMargin
        + ", settlType="
        + this.settlType
        + ", settlPeriod="
        + this.settlPeriod
        + "]";
  }
}
