// Code generated by fin-protoc. DO NOT EDIT.
package com.finproto.bjse.trade.messages;

import com.finproto.codec.BinaryCodec;
import io.netty.buffer.ByteBuf;
import java.util.Objects;

public class ExtendNewOrder010 implements BinaryCodec {
  private long stopPx;
  private long minQty;
  private short maxPriceLevels;
  private String timeInForce;
  private String cashMargin;
  private String settlType;
  private String settlPeriod;

  public long getStopPx() {
    return this.stopPx;
  }

  public void setStopPx(long stopPx) {
    this.stopPx = stopPx;
  }

  public long getMinQty() {
    return this.minQty;
  }

  public void setMinQty(long minQty) {
    this.minQty = minQty;
  }

  public short getMaxPriceLevels() {
    return this.maxPriceLevels;
  }

  public void setMaxPriceLevels(short maxPriceLevels) {
    this.maxPriceLevels = maxPriceLevels;
  }

  public String getTimeInForce() {
    return this.timeInForce;
  }

  public void setTimeInForce(String timeInForce) {
    this.timeInForce = timeInForce;
  }

  public String getCashMargin() {
    return this.cashMargin;
  }

  public void setCashMargin(String cashMargin) {
    this.cashMargin = cashMargin;
  }

  public String getSettlType() {
    return this.settlType;
  }

  public void setSettlType(String settlType) {
    this.settlType = settlType;
  }

  public String getSettlPeriod() {
    return this.settlPeriod;
  }

  public void setSettlPeriod(String settlPeriod) {
    this.settlPeriod = settlPeriod;
  }

  @Override
  public void encode(ByteBuf byteBuf) {
    byteBuf.writeLongLE(this.stopPx);
    byteBuf.writeLongLE(this.minQty);
    byteBuf.writeShortLE(this.maxPriceLevels);
    writeFixedString(byteBuf, this.timeInForce, 1);
    writeFixedString(byteBuf, this.cashMargin, 1);
    writeFixedString(byteBuf, this.settlType, 1);
    writeFixedString(byteBuf, this.settlPeriod, 1);
  }

  @Override
  public void decode(ByteBuf byteBuf) {
    this.stopPx = byteBuf.readLongLE();
    this.minQty = byteBuf.readLongLE();
    this.maxPriceLevels = byteBuf.readShortLE();
    this.timeInForce = readFixedString(byteBuf, 1);
    this.cashMargin = readFixedString(byteBuf, 1);
    this.settlType = readFixedString(byteBuf, 1);
    this.settlPeriod = readFixedString(byteBuf, 1);
  }

  @Override
  public int hashCode() {
    return Objects.hash(
        stopPx, minQty, maxPriceLevels, timeInForce, cashMargin, settlType, settlPeriod);
  }

  @Override
  public boolean equals(Object obj) {
    if (this == obj) {
      return true;
    }
    if (null == obj || getClass() != obj.getClass()) {
      return false;
    }
    ExtendNewOrder010 orther_ = (ExtendNewOrder010) obj;
    return Objects.equals(stopPx, orther_.stopPx)
        && Objects.equals(minQty, orther_.minQty)
        && Objects.equals(maxPriceLevels, orther_.maxPriceLevels)
        && Objects.equals(timeInForce, orther_.timeInForce)
        && Objects.equals(cashMargin, orther_.cashMargin)
        && Objects.equals(settlType, orther_.settlType)
        && Objects.equals(settlPeriod, orther_.settlPeriod);
  }

  @Override
  public String toString() {
    return "ExtendNewOrder010 ["
        + "stopPx="
        + this.stopPx
        + ", minQty="
        + this.minQty
        + ", maxPriceLevels="
        + this.maxPriceLevels
        + ", timeInForce="
        + this.timeInForce
        + ", cashMargin="
        + this.cashMargin
        + ", settlType="
        + this.settlType
        + ", settlPeriod="
        + this.settlPeriod
        + "]";
  }
}
