// Code generated by fin-protoc. DO NOT EDIT.
package com.finproto.bjse.trade.messages;

import com.finproto.codec.BinaryCodec;
import io.netty.buffer.ByteBuf;
import java.util.Objects;

public class QuoteExtend070 implements BinaryCodec {
  private String branchId;
  private String quoteId;
  private String quoteRespId;
  private byte privateQuote;
  private long validUntilTime;
  private byte priceType;
  private byte cashMargin;
  private String counterPartyPbuid;
  private String memo;

  public String getBranchId() {
    return this.branchId;
  }

  public void setBranchId(String branchId) {
    this.branchId = branchId;
  }

  public String getQuoteId() {
    return this.quoteId;
  }

  public void setQuoteId(String quoteId) {
    this.quoteId = quoteId;
  }

  public String getQuoteRespId() {
    return this.quoteRespId;
  }

  public void setQuoteRespId(String quoteRespId) {
    this.quoteRespId = quoteRespId;
  }

  public byte getPrivateQuote() {
    return this.privateQuote;
  }

  public void setPrivateQuote(byte privateQuote) {
    this.privateQuote = privateQuote;
  }

  public long getValidUntilTime() {
    return this.validUntilTime;
  }

  public void setValidUntilTime(long validUntilTime) {
    this.validUntilTime = validUntilTime;
  }

  public byte getPriceType() {
    return this.priceType;
  }

  public void setPriceType(byte priceType) {
    this.priceType = priceType;
  }

  public byte getCashMargin() {
    return this.cashMargin;
  }

  public void setCashMargin(byte cashMargin) {
    this.cashMargin = cashMargin;
  }

  public String getCounterPartyPbuid() {
    return this.counterPartyPbuid;
  }

  public void setCounterPartyPbuid(String counterPartyPbuid) {
    this.counterPartyPbuid = counterPartyPbuid;
  }

  public String getMemo() {
    return this.memo;
  }

  public void setMemo(String memo) {
    this.memo = memo;
  }

  @Override
  public void encode(ByteBuf byteBuf) {
    writeFixedString(byteBuf, this.branchId, 2);
    writeFixedString(byteBuf, this.quoteId, 10);
    writeFixedString(byteBuf, this.quoteRespId, 10);
    byteBuf.writeByte(this.privateQuote);
    byteBuf.writeLongLE(this.validUntilTime);
    byteBuf.writeByte(this.priceType);
    byteBuf.writeByte(this.cashMargin);
    writeFixedString(byteBuf, this.counterPartyPbuid, 6);
    writeFixedString(byteBuf, this.memo, 120);
  }

  @Override
  public void decode(ByteBuf byteBuf) {
    this.branchId = readFixedString(byteBuf, 2);
    this.quoteId = readFixedString(byteBuf, 10);
    this.quoteRespId = readFixedString(byteBuf, 10);
    this.privateQuote = byteBuf.readByte();
    this.validUntilTime = byteBuf.readLongLE();
    this.priceType = byteBuf.readByte();
    this.cashMargin = byteBuf.readByte();
    this.counterPartyPbuid = readFixedString(byteBuf, 6);
    this.memo = readFixedString(byteBuf, 120);
  }

  @Override
  public int hashCode() {
    return Objects.hash(
        branchId,
        quoteId,
        quoteRespId,
        privateQuote,
        validUntilTime,
        priceType,
        cashMargin,
        counterPartyPbuid,
        memo);
  }

  @Override
  public boolean equals(Object obj) {
    if (this == obj) {
      return true;
    }
    if (null == obj || getClass() != obj.getClass()) {
      return false;
    }
    QuoteExtend070 orther_ = (QuoteExtend070) obj;
    return Objects.equals(branchId, orther_.branchId)
        && Objects.equals(quoteId, orther_.quoteId)
        && Objects.equals(quoteRespId, orther_.quoteRespId)
        && Objects.equals(privateQuote, orther_.privateQuote)
        && Objects.equals(validUntilTime, orther_.validUntilTime)
        && Objects.equals(priceType, orther_.priceType)
        && Objects.equals(cashMargin, orther_.cashMargin)
        && Objects.equals(counterPartyPbuid, orther_.counterPartyPbuid)
        && Objects.equals(memo, orther_.memo);
  }

  @Override
  public String toString() {
    return "QuoteExtend070 ["
        + "branchId="
        + this.branchId
        + ", quoteId="
        + this.quoteId
        + ", quoteRespId="
        + this.quoteRespId
        + ", privateQuote="
        + this.privateQuote
        + ", validUntilTime="
        + this.validUntilTime
        + ", priceType="
        + this.priceType
        + ", cashMargin="
        + this.cashMargin
        + ", counterPartyPbuid="
        + this.counterPartyPbuid
        + ", memo="
        + this.memo
        + "]";
  }
}
