// Code generated by fin-protoc. DO NOT EDIT.
package com.finproto.bjse.trade.messages;

import com.finproto.codec.BinaryCodec;
import io.netty.buffer.ByteBuf;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.function.Supplier;

public class QuoteResponse implements BinaryCodec {
  private String applId;
  private String reportingPbuid;
  private String submittingPbuid;
  private String securityId;
  private String securityIdsource;
  private short ownerType;
  private String clearingFirm;
  private long transactTime;
  private String userInfo;
  private String clOrdId;
  private String accountId;
  private String branchId;
  private String quoteRespId;
  private byte quoteRespType;
  private byte side;
  private long validUntilTime;
  private byte quoteType;
  private byte priceType;
  private List<NoQuote> noQuote;
  private BinaryCodec applExtend;

  public String getApplId() {
    return this.applId;
  }

  public void setApplId(String applId) {
    this.applId = applId;
  }

  public String getReportingPbuid() {
    return this.reportingPbuid;
  }

  public void setReportingPbuid(String reportingPbuid) {
    this.reportingPbuid = reportingPbuid;
  }

  public String getSubmittingPbuid() {
    return this.submittingPbuid;
  }

  public void setSubmittingPbuid(String submittingPbuid) {
    this.submittingPbuid = submittingPbuid;
  }

  public String getSecurityId() {
    return this.securityId;
  }

  public void setSecurityId(String securityId) {
    this.securityId = securityId;
  }

  public String getSecurityIdsource() {
    return this.securityIdsource;
  }

  public void setSecurityIdsource(String securityIdsource) {
    this.securityIdsource = securityIdsource;
  }

  public short getOwnerType() {
    return this.ownerType;
  }

  public void setOwnerType(short ownerType) {
    this.ownerType = ownerType;
  }

  public String getClearingFirm() {
    return this.clearingFirm;
  }

  public void setClearingFirm(String clearingFirm) {
    this.clearingFirm = clearingFirm;
  }

  public long getTransactTime() {
    return this.transactTime;
  }

  public void setTransactTime(long transactTime) {
    this.transactTime = transactTime;
  }

  public String getUserInfo() {
    return this.userInfo;
  }

  public void setUserInfo(String userInfo) {
    this.userInfo = userInfo;
  }

  public String getClOrdId() {
    return this.clOrdId;
  }

  public void setClOrdId(String clOrdId) {
    this.clOrdId = clOrdId;
  }

  public String getAccountId() {
    return this.accountId;
  }

  public void setAccountId(String accountId) {
    this.accountId = accountId;
  }

  public String getBranchId() {
    return this.branchId;
  }

  public void setBranchId(String branchId) {
    this.branchId = branchId;
  }

  public String getQuoteRespId() {
    return this.quoteRespId;
  }

  public void setQuoteRespId(String quoteRespId) {
    this.quoteRespId = quoteRespId;
  }

  public byte getQuoteRespType() {
    return this.quoteRespType;
  }

  public void setQuoteRespType(byte quoteRespType) {
    this.quoteRespType = quoteRespType;
  }

  public byte getSide() {
    return this.side;
  }

  public void setSide(byte side) {
    this.side = side;
  }

  public long getValidUntilTime() {
    return this.validUntilTime;
  }

  public void setValidUntilTime(long validUntilTime) {
    this.validUntilTime = validUntilTime;
  }

  public byte getQuoteType() {
    return this.quoteType;
  }

  public void setQuoteType(byte quoteType) {
    this.quoteType = quoteType;
  }

  public byte getPriceType() {
    return this.priceType;
  }

  public void setPriceType(byte priceType) {
    this.priceType = priceType;
  }

  public List<NoQuote> getNoQuote() {
    return this.noQuote;
  }

  public void setNoQuote(List<NoQuote> noQuote) {
    this.noQuote = noQuote;
  }

  public BinaryCodec getApplExtend() {
    return this.applExtend;
  }

  public void setApplExtend(BinaryCodec applExtend) {
    this.applExtend = applExtend;
  }

  @Override
  public void encode(ByteBuf byteBuf) {
    writeFixedString(byteBuf, this.applId, 3);
    writeFixedString(byteBuf, this.reportingPbuid, 6);
    writeFixedString(byteBuf, this.submittingPbuid, 6);
    writeFixedString(byteBuf, this.securityId, 8);
    writeFixedString(byteBuf, this.securityIdsource, 4);
    byteBuf.writeShortLE(this.ownerType);
    writeFixedString(byteBuf, this.clearingFirm, 2);
    byteBuf.writeLongLE(this.transactTime);
    writeFixedString(byteBuf, this.userInfo, 32);
    writeFixedString(byteBuf, this.clOrdId, 10);
    writeFixedString(byteBuf, this.accountId, 10);
    writeFixedString(byteBuf, this.branchId, 2);
    writeFixedString(byteBuf, this.quoteRespId, 10);
    byteBuf.writeByte(this.quoteRespType);
    byteBuf.writeByte(this.side);
    byteBuf.writeLongLE(this.validUntilTime);
    byteBuf.writeByte(this.quoteType);
    byteBuf.writeByte(this.priceType);
    if (null == this.noQuote || this.noQuote.size() == 0) {
      byteBuf.writeShort(0);
    } else {
      byteBuf.writeShortLE((short) this.noQuote.size());
      for (int i = 0; i < this.noQuote.size(); i++) {
        this.noQuote.get(i).encode(byteBuf);
      }
    }
    if (null != this.applExtend) {
      this.applExtend.encode(byteBuf);
    }
  }

  @Override
  public void decode(ByteBuf byteBuf) {
    this.applId = readFixedString(byteBuf, 3);
    this.reportingPbuid = readFixedString(byteBuf, 6);
    this.submittingPbuid = readFixedString(byteBuf, 6);
    this.securityId = readFixedString(byteBuf, 8);
    this.securityIdsource = readFixedString(byteBuf, 4);
    this.ownerType = byteBuf.readShortLE();
    this.clearingFirm = readFixedString(byteBuf, 2);
    this.transactTime = byteBuf.readLongLE();
    this.userInfo = readFixedString(byteBuf, 32);
    this.clOrdId = readFixedString(byteBuf, 10);
    this.accountId = readFixedString(byteBuf, 10);
    this.branchId = readFixedString(byteBuf, 2);
    this.quoteRespId = readFixedString(byteBuf, 10);
    this.quoteRespType = byteBuf.readByte();
    this.side = byteBuf.readByte();
    this.validUntilTime = byteBuf.readLongLE();
    this.quoteType = byteBuf.readByte();
    this.priceType = byteBuf.readByte();
    short noQuoteSize = byteBuf.readShortLE();
    if (noQuoteSize > 0) {
      this.noQuote = new ArrayList<>();
      for (int i = 0; i < noQuoteSize; i++) {
        NoQuote noQuote_ = new NoQuote();
        noQuote_.decode(byteBuf);
        this.noQuote.add(noQuote_);
      }
    }
    this.applExtend = createApplExtend(this.applId);
    this.applExtend.decode(byteBuf);
  }

  private static final Map<String, Supplier<BinaryCodec>> applExtendMap = new HashMap<>();

  static {
    applExtendMap.put("070", QuoteResponseExtend070::new);
  }

  private BinaryCodec createApplExtend(String applId) {
    Supplier<BinaryCodec> supplier = applExtendMap.get(applId);
    if (null == supplier) {
      throw new IllegalArgumentException("Unsupported ApplID:" + applId);
    }
    return supplier.get();
  }

  @Override
  public int hashCode() {
    return Objects.hash(
        applId,
        reportingPbuid,
        submittingPbuid,
        securityId,
        securityIdsource,
        ownerType,
        clearingFirm,
        transactTime,
        userInfo,
        clOrdId,
        accountId,
        branchId,
        quoteRespId,
        quoteRespType,
        side,
        validUntilTime,
        quoteType,
        priceType,
        noQuote,
        applExtend);
  }

  @Override
  public boolean equals(Object obj) {
    if (this == obj) {
      return true;
    }
    if (null == obj || getClass() != obj.getClass()) {
      return false;
    }
    QuoteResponse orther_ = (QuoteResponse) obj;
    return Objects.equals(applId, orther_.applId)
        && Objects.equals(reportingPbuid, orther_.reportingPbuid)
        && Objects.equals(submittingPbuid, orther_.submittingPbuid)
        && Objects.equals(securityId, orther_.securityId)
        && Objects.equals(securityIdsource, orther_.securityIdsource)
        && Objects.equals(ownerType, orther_.ownerType)
        && Objects.equals(clearingFirm, orther_.clearingFirm)
        && Objects.equals(transactTime, orther_.transactTime)
        && Objects.equals(userInfo, orther_.userInfo)
        && Objects.equals(clOrdId, orther_.clOrdId)
        && Objects.equals(accountId, orther_.accountId)
        && Objects.equals(branchId, orther_.branchId)
        && Objects.equals(quoteRespId, orther_.quoteRespId)
        && Objects.equals(quoteRespType, orther_.quoteRespType)
        && Objects.equals(side, orther_.side)
        && Objects.equals(validUntilTime, orther_.validUntilTime)
        && Objects.equals(quoteType, orther_.quoteType)
        && Objects.equals(priceType, orther_.priceType)
        && Objects.equals(noQuote, orther_.noQuote)
        && Objects.equals(applExtend, orther_.applExtend);
  }

  @Override
  public String toString() {
    return "QuoteResponse ["
        + "applId="
        + this.applId
        + ", reportingPbuid="
        + this.reportingPbuid
        + ", submittingPbuid="
        + this.submittingPbuid
        + ", securityId="
        + this.securityId
        + ", securityIdsource="
        + this.securityIdsource
        + ", ownerType="
        + this.ownerType
        + ", clearingFirm="
        + this.clearingFirm
        + ", transactTime="
        + this.transactTime
        + ", userInfo="
        + this.userInfo
        + ", clOrdId="
        + this.clOrdId
        + ", accountId="
        + this.accountId
        + ", branchId="
        + this.branchId
        + ", quoteRespId="
        + this.quoteRespId
        + ", quoteRespType="
        + this.quoteRespType
        + ", side="
        + this.side
        + ", validUntilTime="
        + this.validUntilTime
        + ", quoteType="
        + this.quoteType
        + ", priceType="
        + this.priceType
        + ", noQuote="
        + this.noQuote
        + ", applExtend="
        + this.applExtend
        + "]";
  }

  // Code generated by fin-protoc. DO NOT EDIT.
  public static class NoQuote implements BinaryCodec {
    private String quoteId;
    private long quotePrice;
    private long quoteQty;

    public String getQuoteId() {
      return this.quoteId;
    }

    public void setQuoteId(String quoteId) {
      this.quoteId = quoteId;
    }

    public long getQuotePrice() {
      return this.quotePrice;
    }

    public void setQuotePrice(long quotePrice) {
      this.quotePrice = quotePrice;
    }

    public long getQuoteQty() {
      return this.quoteQty;
    }

    public void setQuoteQty(long quoteQty) {
      this.quoteQty = quoteQty;
    }

    @Override
    public void encode(ByteBuf byteBuf) {
      writeFixedString(byteBuf, this.quoteId, 10);
      byteBuf.writeLongLE(this.quotePrice);
      byteBuf.writeLongLE(this.quoteQty);
    }

    @Override
    public void decode(ByteBuf byteBuf) {
      this.quoteId = readFixedString(byteBuf, 10);
      this.quotePrice = byteBuf.readLongLE();
      this.quoteQty = byteBuf.readLongLE();
    }

    @Override
    public int hashCode() {
      return Objects.hash(quoteId, quotePrice, quoteQty);
    }

    @Override
    public boolean equals(Object obj) {
      if (this == obj) {
        return true;
      }
      if (null == obj || getClass() != obj.getClass()) {
        return false;
      }
      NoQuote orther_ = (NoQuote) obj;
      return Objects.equals(quoteId, orther_.quoteId)
          && Objects.equals(quotePrice, orther_.quotePrice)
          && Objects.equals(quoteQty, orther_.quoteQty);
    }

    @Override
    public String toString() {
      return "NoQuote ["
          + "quoteId="
          + this.quoteId
          + ", quotePrice="
          + this.quotePrice
          + ", quoteQty="
          + this.quoteQty
          + "]";
    }
  }
}
