// Code generated by fin-protoc. DO NOT EDIT.
package com.finproto.bjse.trade.messages;

import com.finproto.codec.BinaryCodec;
import io.netty.buffer.ByteBuf;
import java.util.Objects;

public class ReportExtend010 implements BinaryCodec {
  private byte cashMargin;
  private byte settlType;
  private byte settlPeriod;

  public byte getCashMargin() {
    return this.cashMargin;
  }

  public void setCashMargin(byte cashMargin) {
    this.cashMargin = cashMargin;
  }

  public byte getSettlType() {
    return this.settlType;
  }

  public void setSettlType(byte settlType) {
    this.settlType = settlType;
  }

  public byte getSettlPeriod() {
    return this.settlPeriod;
  }

  public void setSettlPeriod(byte settlPeriod) {
    this.settlPeriod = settlPeriod;
  }

  @Override
  public void encode(ByteBuf byteBuf) {
    byteBuf.writeByte(this.cashMargin);
    byteBuf.writeByte(this.settlType);
    byteBuf.writeByte(this.settlPeriod);
  }

  @Override
  public void decode(ByteBuf byteBuf) {
    this.cashMargin = byteBuf.readByte();
    this.settlType = byteBuf.readByte();
    this.settlPeriod = byteBuf.readByte();
  }

  @Override
  public int hashCode() {
    return Objects.hash(cashMargin, settlType, settlPeriod);
  }

  @Override
  public boolean equals(Object obj) {
    if (this == obj) {
      return true;
    }
    if (null == obj || getClass() != obj.getClass()) {
      return false;
    }
    ReportExtend010 orther_ = (ReportExtend010) obj;
    return Objects.equals(cashMargin, orther_.cashMargin)
        && Objects.equals(settlType, orther_.settlType)
        && Objects.equals(settlPeriod, orther_.settlPeriod);
  }

  @Override
  public String toString() {
    return "ReportExtend010 ["
        + "cashMargin="
        + this.cashMargin
        + ", settlType="
        + this.settlType
        + ", settlPeriod="
        + this.settlPeriod
        + "]";
  }
}
