// Code generated by fin-protoc. DO NOT EDIT.
package com.finproto.bjse.trade.messages;

import com.finproto.codec.BinaryCodec;
import io.netty.buffer.ByteBuf;
import java.util.Objects;

public class ReportExtend010 implements BinaryCodec {
  private String cashMargin;
  private String settlType;
  private String settlPeriod;

  public String getCashMargin() {
    return this.cashMargin;
  }

  public void setCashMargin(String cashMargin) {
    this.cashMargin = cashMargin;
  }

  public String getSettlType() {
    return this.settlType;
  }

  public void setSettlType(String settlType) {
    this.settlType = settlType;
  }

  public String getSettlPeriod() {
    return this.settlPeriod;
  }

  public void setSettlPeriod(String settlPeriod) {
    this.settlPeriod = settlPeriod;
  }

  @Override
  public void encode(ByteBuf byteBuf) {
    writeFixedString(byteBuf, this.cashMargin, 1);
    writeFixedString(byteBuf, this.settlType, 1);
    writeFixedString(byteBuf, this.settlPeriod, 1);
  }

  @Override
  public void decode(ByteBuf byteBuf) {
    this.cashMargin = readFixedString(byteBuf, 1);
    this.settlType = readFixedString(byteBuf, 1);
    this.settlPeriod = readFixedString(byteBuf, 1);
  }

  @Override
  public int hashCode() {
    return Objects.hash(cashMargin, settlType, settlPeriod);
  }

  @Override
  public boolean equals(Object obj) {
    if (this == obj) {
      return true;
    }
    if (null == obj || getClass() != obj.getClass()) {
      return false;
    }
    ReportExtend010 orther_ = (ReportExtend010) obj;
    return Objects.equals(cashMargin, orther_.cashMargin)
        && Objects.equals(settlType, orther_.settlType)
        && Objects.equals(settlPeriod, orther_.settlPeriod);
  }

  @Override
  public String toString() {
    return "ReportExtend010 ["
        + "cashMargin="
        + this.cashMargin
        + ", settlType="
        + this.settlType
        + ", settlPeriod="
        + this.settlPeriod
        + "]";
  }
}
