// Code generated by fin-protoc. DO NOT EDIT.
package com.finproto.bjse.trade.messages;

import com.finproto.codec.BinaryCodec;
import io.netty.buffer.ByteBuf;
import java.util.Objects;

public class TradingSessionStatus implements BinaryCodec {
  private String marketId;
  private String marketSegmentId;
  private String tradingSessionId;
  private String tradingSessionSubId;
  private byte tradSesStatus;
  private long tradSesStartTime;

  public String getMarketId() {
    return this.marketId;
  }

  public void setMarketId(String marketId) {
    this.marketId = marketId;
  }

  public String getMarketSegmentId() {
    return this.marketSegmentId;
  }

  public void setMarketSegmentId(String marketSegmentId) {
    this.marketSegmentId = marketSegmentId;
  }

  public String getTradingSessionId() {
    return this.tradingSessionId;
  }

  public void setTradingSessionId(String tradingSessionId) {
    this.tradingSessionId = tradingSessionId;
  }

  public String getTradingSessionSubId() {
    return this.tradingSessionSubId;
  }

  public void setTradingSessionSubId(String tradingSessionSubId) {
    this.tradingSessionSubId = tradingSessionSubId;
  }

  public byte getTradSesStatus() {
    return this.tradSesStatus;
  }

  public void setTradSesStatus(byte tradSesStatus) {
    this.tradSesStatus = tradSesStatus;
  }

  public long getTradSesStartTime() {
    return this.tradSesStartTime;
  }

  public void setTradSesStartTime(long tradSesStartTime) {
    this.tradSesStartTime = tradSesStartTime;
  }

  @Override
  public void encode(ByteBuf byteBuf) {
    writeFixedString(byteBuf, this.marketId, 3);
    writeFixedString(byteBuf, this.marketSegmentId, 3);
    writeFixedString(byteBuf, this.tradingSessionId, 3);
    writeFixedString(byteBuf, this.tradingSessionSubId, 3);
    byteBuf.writeByte(this.tradSesStatus);
    byteBuf.writeLongLE(this.tradSesStartTime);
  }

  @Override
  public void decode(ByteBuf byteBuf) {
    this.marketId = readFixedString(byteBuf, 3);
    this.marketSegmentId = readFixedString(byteBuf, 3);
    this.tradingSessionId = readFixedString(byteBuf, 3);
    this.tradingSessionSubId = readFixedString(byteBuf, 3);
    this.tradSesStatus = byteBuf.readByte();
    this.tradSesStartTime = byteBuf.readLongLE();
  }

  @Override
  public int hashCode() {
    return Objects.hash(
        marketId,
        marketSegmentId,
        tradingSessionId,
        tradingSessionSubId,
        tradSesStatus,
        tradSesStartTime);
  }

  @Override
  public boolean equals(Object obj) {
    if (this == obj) {
      return true;
    }
    if (null == obj || getClass() != obj.getClass()) {
      return false;
    }
    TradingSessionStatus orther_ = (TradingSessionStatus) obj;
    return Objects.equals(marketId, orther_.marketId)
        && Objects.equals(marketSegmentId, orther_.marketSegmentId)
        && Objects.equals(tradingSessionId, orther_.tradingSessionId)
        && Objects.equals(tradingSessionSubId, orther_.tradingSessionSubId)
        && Objects.equals(tradSesStatus, orther_.tradSesStatus)
        && Objects.equals(tradSesStartTime, orther_.tradSesStartTime);
  }

  @Override
  public String toString() {
    return "TradingSessionStatus ["
        + "marketId="
        + this.marketId
        + ", marketSegmentId="
        + this.marketSegmentId
        + ", tradingSessionId="
        + this.tradingSessionId
        + ", tradingSessionSubId="
        + this.tradingSessionSubId
        + ", tradSesStatus="
        + this.tradSesStatus
        + ", tradSesStartTime="
        + this.tradSesStartTime
        + "]";
  }
}
