// Code generated by fin-protoc. DO NOT EDIT.
package com.finproto.bjse.trade.messages;

import com.finproto.codec.BinaryCodec;
import io.netty.buffer.ByteBuf;

public class TradeCaptureCofirmExtend060 implements BinaryCodec {

  @Override
  public void encode(ByteBuf byteBuf) {}

  @Override
  public void decode(ByteBuf byteBuf) {}

  @Override
  public int hashCode() {
    return this.hashCode();
  }

  @Override
  public boolean equals(Object obj) {
    if (this == obj) {
      return true;
    }
    if (null == obj || getClass() != obj.getClass()) {
      return false;
    }
    return true;
  }

  @Override
  public String toString() {
    return "TradeCaptureCofirmExtend060 []";
  }
}
