// Code generated by fin-protoc. DO NOT EDIT.
package com.finproto.bjse.trade.messages;

import com.finproto.codec.BinaryCodec;
import io.netty.buffer.ByteBuf;
import java.util.Objects;

public class TradeCaptureReportAckExtend031 implements BinaryCodec {
  private String memberId;
  private String traderCode;
  private String counterPartyMemberId;
  private String counterPartyTraderCode;
  private byte settlType;
  private byte settlPeriod;
  private byte cashMargin;
  private String memo;

  public String getMemberId() {
    return this.memberId;
  }

  public void setMemberId(String memberId) {
    this.memberId = memberId;
  }

  public String getTraderCode() {
    return this.traderCode;
  }

  public void setTraderCode(String traderCode) {
    this.traderCode = traderCode;
  }

  public String getCounterPartyMemberId() {
    return this.counterPartyMemberId;
  }

  public void setCounterPartyMemberId(String counterPartyMemberId) {
    this.counterPartyMemberId = counterPartyMemberId;
  }

  public String getCounterPartyTraderCode() {
    return this.counterPartyTraderCode;
  }

  public void setCounterPartyTraderCode(String counterPartyTraderCode) {
    this.counterPartyTraderCode = counterPartyTraderCode;
  }

  public byte getSettlType() {
    return this.settlType;
  }

  public void setSettlType(byte settlType) {
    this.settlType = settlType;
  }

  public byte getSettlPeriod() {
    return this.settlPeriod;
  }

  public void setSettlPeriod(byte settlPeriod) {
    this.settlPeriod = settlPeriod;
  }

  public byte getCashMargin() {
    return this.cashMargin;
  }

  public void setCashMargin(byte cashMargin) {
    this.cashMargin = cashMargin;
  }

  public String getMemo() {
    return this.memo;
  }

  public void setMemo(String memo) {
    this.memo = memo;
  }

  @Override
  public void encode(ByteBuf byteBuf) {
    writeFixedString(byteBuf, this.memberId, 6);
    writeFixedString(byteBuf, this.traderCode, 5);
    writeFixedString(byteBuf, this.counterPartyMemberId, 6);
    writeFixedString(byteBuf, this.counterPartyTraderCode, 5);
    byteBuf.writeByte(this.settlType);
    byteBuf.writeByte(this.settlPeriod);
    byteBuf.writeByte(this.cashMargin);
    writeFixedString(byteBuf, this.memo, 120);
  }

  @Override
  public void decode(ByteBuf byteBuf) {
    this.memberId = readFixedString(byteBuf, 6);
    this.traderCode = readFixedString(byteBuf, 5);
    this.counterPartyMemberId = readFixedString(byteBuf, 6);
    this.counterPartyTraderCode = readFixedString(byteBuf, 5);
    this.settlType = byteBuf.readByte();
    this.settlPeriod = byteBuf.readByte();
    this.cashMargin = byteBuf.readByte();
    this.memo = readFixedString(byteBuf, 120);
  }

  @Override
  public int hashCode() {
    return Objects.hash(
        memberId,
        traderCode,
        counterPartyMemberId,
        counterPartyTraderCode,
        settlType,
        settlPeriod,
        cashMargin,
        memo);
  }

  @Override
  public boolean equals(Object obj) {
    if (this == obj) {
      return true;
    }
    if (null == obj || getClass() != obj.getClass()) {
      return false;
    }
    TradeCaptureReportAckExtend031 orther_ = (TradeCaptureReportAckExtend031) obj;
    return Objects.equals(memberId, orther_.memberId)
        && Objects.equals(traderCode, orther_.traderCode)
        && Objects.equals(counterPartyMemberId, orther_.counterPartyMemberId)
        && Objects.equals(counterPartyTraderCode, orther_.counterPartyTraderCode)
        && Objects.equals(settlType, orther_.settlType)
        && Objects.equals(settlPeriod, orther_.settlPeriod)
        && Objects.equals(cashMargin, orther_.cashMargin)
        && Objects.equals(memo, orther_.memo);
  }

  @Override
  public String toString() {
    return "TradeCaptureReportAckExtend031 ["
        + "memberId="
        + this.memberId
        + ", traderCode="
        + this.traderCode
        + ", counterPartyMemberId="
        + this.counterPartyMemberId
        + ", counterPartyTraderCode="
        + this.counterPartyTraderCode
        + ", settlType="
        + this.settlType
        + ", settlPeriod="
        + this.settlPeriod
        + ", cashMargin="
        + this.cashMargin
        + ", memo="
        + this.memo
        + "]";
  }
}
